//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonolitoZaqueu2.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabProduto
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Valor { get; set; }
        public string Foto { get; set; }
        public string Descricao { get; set; }
        public string Parcelamento { get; set; }
    }
}
